### ISSUE TITLE
Refining the highlight matching if/else

### ISSUE THREAD

**Issue by singalen** [kropp/intellij-makefile#122]
Thanks a lot for #100!
Some additions:
* `else` should be highlighted, and should highlight its matching if/endif too. `else` can also be miles away from a matching `if`.
* this may mean the need to highlight all of a [complex conditional](https://www.gnu.org/savannah-checkouts/gnu/make/manual/html_node/Conditional-Syntax.html#Conditional-Syntax).

Ctrl-M (go to matching bracket/operator) should probably cycle along all `else if`/`else`s.

Speaking of complex conditionals, their matching element seems broken. Here:

```
ifeq (1,2)

 ifeq (2,3)
  A := B
 else ifeq (3,4)
  A := C
 endif

endif
```
the last `endif` is matched with the second `ifeq`, while it should match the first one.

**Comment by kropp** [comment]
Fixed

**Comment by singalen** [comment]
I'm afraid I still see the described problem with if/else/endif matching in 2.9.2.
Should I register a new issue?

![Screen Shot 2020-04-22 at 17 00 31](https://user-images.githubusercontent.com/151199/80044979-f789ad00-84ba-11ea-8b06-9d58923e373b.png)
![Screen Shot 2020-04-22 at 17 00 27](https://user-images.githubusercontent.com/151199/80044982-f789ad00-84ba-11ea-9e56-c21e7cc31684.png)
![Screen Shot 2020-04-22 at 17 00 42](https://user-images.githubusercontent.com/151199/80044974-f6588000-84ba-11ea-9282-290b46884d7e.png)
![Screen Shot 2020-04-22 at 17 03 20](https://user-images.githubusercontent.com/151199/80045056-361f6780-84bb-11ea-877a-e01690830dd4.png)
